-- Make the 'propiedades' bucket public
-- This allows accessing files via getPublicUrl without a signed token.
update storage.buckets
set "public" = true
where id = 'propiedades';

-- POLICY 1: Allow public read access (SELECT) to everyone
-- This is required for the public URLs to work for everyone (even unauthenticated users).
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'propiedades' );

-- POLICY 2: Allow authenticated users to upload (INSERT)
-- Ideally, we rely on the backend generating Signed Upload URLs (which bypass RLS).
-- However, it is good practice to allow authenticated inserts if you switch to client-side uploads.
-- If you ONLY want to use Signed Upload URLs generated by the backend, you can essentially disallow direct inserts 
-- (or keep this policy and it won't be used if you don't use client-side supabase client).
-- But to "configure that only a logged in agent can upload", implies we want some restriction.
-- Since the backend uses the Service Role (admin) to generate the signed URL, that signed URL allows upload.
-- We can block all other direct inserts.
create policy "Authenticated Upload"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'propiedades' );

-- POLICY 3: Allow users to update/delete their own files (Optional/Advanced)
-- For now, if deletion is handled by backend (Service Role), no extra policy needed for delete.
